micronaut:
  server:
    port: 5000
  application:
    name: mnFirebaseTenantProviders
  router:
    static-resources:
      main:
        paths: classpath:views
        mapping: /**
        enabled: true
---
logger:
  levels:
    mn.firebase: DEBUG
---
gcp:
  project-id: 'your-project-id'
  credentials:
    location: /path/to/your/credentials.json
